eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} # The URL of the Eureka Server
    register-with-eureka: true # Whether to register this application with Eureka (default is true for clients)
    fetch-registry: true
  instance:
    hostname: localhost
